arch:
  - aarch64
  - amd64
backup_exclude:
  - "**/cache/"
  - "**/log/"
description: >
  VS Code in the browser. Code on any device with a consistent dev
  environment. Access your Home Assistant config files directly, edit
  add-ons, automate, and develop from the comfort of your browser.
environment:
  PGID: "0"
  PUID: "0"
homeassistant: 2024.1.0
host_network: true
icon: icon.png
image: ghcr.io/rezusnet/code-server-{arch}
ingress: true
ingress_port: 8443
ingress_stream: true
init: false
map:
  - addon_config:rw
  - media:rw
  - share:rw
  - ssl
  - homeassistant_config:rw
  - all_addon_configs:rw
name: Code Server
options:
  env_vars: []
  PGID: 0
  PUID: 0
  data_location: /share/code-server
  TZ: ""
  localdisks: ""
  networkdisks: ""
  cifsusername: ""
  cifspassword: ""
  cifsdomain: ""
  PASSWORD: ""
  SUDO_PASSWORD: ""
  PROXY_DOMAIN: ""
  DEFAULT_WORKSPACE: /config/workspace
  DOCKER_MODS: []
panel_icon: mdi:microsoft-visual-studio-code
panel_admin: true
ports:
  8443/tcp: 8443
ports_description:
  8443/tcp: VS Code Web UI
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
schema:
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
  PGID: int
  PUID: int
  data_location: str
  TZ: str?
  localdisks: str?
  networkdisks: str?
  cifsusername: str?
  cifspassword: str?
  cifsdomain: str?
  PASSWORD: password?
  SUDO_PASSWORD: password?
  PROXY_DOMAIN: str?
  DEFAULT_WORKSPACE: str?
  DOCKER_MODS:
    - match(^linuxserver/mods:code-server-[a-z0-9-]+$)?
slug: code-server
udev: true
url: https://coder.com
version: "1.0.0"

