#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set +u

source /usr/local/lib/bashio-standalone.sh

LOCATION="$(bashio::config 'data_location')"
if [[ "$LOCATION" = "null" || -z "$LOCATION" ]]; then LOCATION=/config; fi
RATE_LIMIT="$(bashio::config 'rate_limit')"
WS_FALLBACK="$(bashio::config 'ws_fallback')"
DEBUG_MODE="$(bashio::config 'debug_mode')"
export DEBUG_MODE

mkdir -p "$LOCATION"

for _ in $(seq 1 30); do
    if ! nc -z localhost 3000 2>/dev/null; then
        break
    fi
    sleep 1
done

if [[ ${RATE_LIMIT,,} = "true" ]]; then
    OPT_RATE_LIMIT="--rate-limit"
fi

if [[ ${WS_FALLBACK,,} = "true" ]]; then
    OPT_WS_FALLBACK="--include-ws-fallback"
fi

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    HOME=$LOCATION exec \
        s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 3000" \
        cd /app/pairdrop s6-setuidgid abc node server/index.js "${OPT_RATE_LIMIT}" "${OPT_WS_FALLBACK}"
else
    HOME=$LOCATION exec \
        s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 3000" \
        cd /app/pairdrop node server/index.js "${OPT_RATE_LIMIT}" "${OPT_WS_FALLBACK}"
fi
