arch:
  - aarch64
  - amd64
description: "Speedtest Tracker - based on linuxserver/docker-speedtest-tracker"
homeassistant: "2024.1.0"
icon: icon.png
image: ghcr.io/rezusnet/speedtest-tracker-{arch}
init: false
name: Speedtest Tracker
options:
  PGID: 0
  PUID: 0
  TZ: ""
  data_location: /share/speedtest-tracker
  env_vars: []
ports:
  80/tcp: 80
ports_description:
  80/tcp: "Web interface"
schema:
  PGID: int
  PUID: int
  TZ: str?
  data_location: str
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
ingress: true
ingress_port: 80
panel_icon: mdi:server
slug: speedtest-tracker
url: https://github.com/linuxserver/docker-speedtest-tracker
version: "1.23.0"
