arch:
  - aarch64
  - amd64
description: "rsnapshot - based on linuxserver/docker-rsnapshot"
homeassistant: "2024.1.0"
icon: icon.png
image: ghcr.io/rezusnet/rsnapshot-{arch}
init: false
name: rsnapshot
options:
  PGID: 0
  PUID: 0
  TZ: ""
  data_location: /share/rsnapshot
  env_vars: []
ports:
  # No ports
ports_description:
  # No ports
schema:
  PGID: int
  PUID: int
  TZ: str?
  data_location: str
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
slug: rsnapshot
url: https://github.com/linuxserver/docker-rsnapshot
version: 1.0.0
