arch:
  - aarch64
  - amd64
description: "Nginx - based on linuxserver/docker-nginx"
homeassistant: "2024.1.0"
icon: icon.png
image: ghcr.io/rezusnet/nginx-{arch}
init: false
name: Nginx
options:
  PGID: 0
  PUID: 0
  TZ: ""
  data_location: /share/nginx
  env_vars: []
ports:
  80/tcp: 80
ports_description:
  80/tcp: "Web interface"
schema:
  PGID: int
  PUID: int
  TZ: str?
  data_location: str
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
ingress: true
ingress_port: 80
panel_icon: mdi:server
slug: nginx
url: https://github.com/linuxserver/docker-nginx
version: "1.30.0"
