arch:
  - aarch64
  - amd64
boot: auto
description: "Automatic addons update by aligning version tag with upstream releases"
image: ghcr.io/rezusnet/addons_updater-{arch}
icon: icon.png
map:
  - addon_config:rw
name: Addons updater
options:
  date_iso8601: true
  env_vars: []
  gitapi: CHANGE_ME
  gituser: tibrezus
  verbose: true
  repository: rezusnet/hassio-addons
schema:
  dry_run: bool?
  gitapi: str
  gitmail: str?
  gituser: str
  repository: str
  verbose: bool?
slug: addons_updater
url: https://github.com/rezusnet/hassio-addons
version: "1.0.0"
