icon: icon.png
homeassistant: "2024.1.0"
name: "Obsidian"
description: "Knowledge base/note-taking app accessible via web desktop"
url: "https://github.com/linuxserver/docker-obsidian"
arch:
  - aarch64
  - amd64
slug: "obsidian"
version: "1.0.0"
webui: "https://[HOST]:[PORT:3001]"
ingress: false
startup: "application"
boot: "auto"
map:
  - config:rw
  - share:rw
options:
  PUID: 1000
  PGID: 1000
  TZ: "Etc/UTC"
  CUSTOM_USER: ""
  PASSWORD: ""
schema:
  PUID: int
  PGID: int
  TZ: str
  CUSTOM_USER: str
  PASSWORD: password
ports:
  3000/tcp: null
  3001/tcp: 3001
ports_description:
  3000/tcp: "Obsidian desktop GUI (HTTP — must be proxied)"
  3001/tcp: "Obsidian desktop GUI (HTTPS)"

