arch:
  - aarch64
  - amd64
description: "SickGear - based on linuxserver/docker-sickgear"
homeassistant: "2024.1.0"
icon: icon.png
image: ghcr.io/rezusnet/sickgear-{arch}
init: false
name: SickGear
options:
  PGID: 0
  PUID: 0
  TZ: ""
  data_location: /share/sickgear
  env_vars: []
ports:
  8081/tcp: 8081
ports_description:
  8081/tcp: "Web interface"
schema:
  PGID: int
  PUID: int
  TZ: str?
  data_location: str
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
ingress: true
ingress_port: 8081
panel_icon: mdi:server
slug: sickgear
url: https://github.com/linuxserver/docker-sickgear
version: 1.0.0
