#!/usr/bin/env bashio
# shellcheck shell=bash
set -e

bashio::log.info "Generating LightRAG configuration..."

mkdir -p /data/rag_storage /data/inputs

ENV_FILE="/app/.env"

cat > "$ENV_FILE" << 'HEADER'
### Auto-generated by Home Assistant LightRAG add-on ###
HEADER

write_env() {
    local key="$1"
    local val="$2"
    if [ -n "$val" ]; then
        echo "${key}=${val}" >> "$ENV_FILE"
    fi
}

write_env "HOST" "0.0.0.0"
write_env "PORT" "9621"
write_env "WORKING_DIR" "/data/rag_storage"
write_env "INPUT_DIR" "/data/inputs"
write_env "TIKTOKEN_CACHE_DIR" "/data/tiktoken"

if bashio::config.has_value 'webui_title'; then
    write_env "WEBUI_TITLE" "$(bashio::config 'webui_title')"
fi

write_env "LLM_BINDING" "$(bashio::config 'llm_binding')"

if bashio::config.has_value 'llm_binding_host'; then
    write_env "LLM_BINDING_HOST" "$(bashio::config 'llm_binding_host')"
fi

if bashio::config.has_value 'llm_binding_api_key'; then
    write_env "LLM_BINDING_API_KEY" "$(bashio::config 'llm_binding_api_key')"
fi

write_env "LLM_MODEL" "$(bashio::config 'llm_model')"

if bashio::config.has_value 'llm_timeout'; then
    write_env "LLM_TIMEOUT" "$(bashio::config 'llm_timeout')"
fi

write_env "EMBEDDING_BINDING" "$(bashio::config 'embedding_binding')"

if bashio::config.has_value 'embedding_binding_host'; then
    write_env "EMBEDDING_BINDING_HOST" "$(bashio::config 'embedding_binding_host')"
fi

if bashio::config.has_value 'embedding_binding_api_key'; then
    write_env "EMBEDDING_BINDING_API_KEY" "$(bashio::config 'embedding_binding_api_key')"
fi

write_env "EMBEDDING_MODEL" "$(bashio::config 'embedding_model')"
write_env "EMBEDDING_DIM" "$(bashio::config 'embedding_dim')"

if bashio::config.has_value 'summary_language'; then
    write_env "SUMMARY_LANGUAGE" "$(bashio::config 'summary_language')"
fi

if bashio::config.has_value 'chunk_size'; then
    write_env "CHUNK_SIZE" "$(bashio::config 'chunk_size')"
fi

if bashio::config.has_value 'max_async'; then
    write_env "MAX_ASYNC" "$(bashio::config 'max_async')"
fi

if bashio::config.has_value 'kv_storage'; then
    write_env "LIGHTRAG_KV_STORAGE" "$(bashio::config 'kv_storage')"
fi

if bashio::config.has_value 'vector_storage'; then
    write_env "LIGHTRAG_VECTOR_STORAGE" "$(bashio::config 'vector_storage')"
fi

if bashio::config.has_value 'graph_storage'; then
    write_env "LIGHTRAG_GRAPH_STORAGE" "$(bashio::config 'graph_storage')"
fi

if bashio::config.has_value 'doc_status_storage'; then
    write_env "LIGHTRAG_DOC_STATUS_STORAGE" "$(bashio::config 'doc_status_storage')"
fi

if bashio::config.has_value 'enable_llm_cache'; then
    if bashio::config.true 'enable_llm_cache'; then
        write_env "ENABLE_LLM_CACHE" "true"
    else
        write_env "ENABLE_LLM_CACHE" "false"
    fi
fi

if bashio::config.has_value 'top_k'; then
    write_env "TOP_K" "$(bashio::config 'top_k')"
fi

if bashio::config.has_value 'auth_accounts'; then
    write_env "AUTH_ACCOUNTS" "$(bashio::config 'auth_accounts')"
fi

if bashio::config.has_value 'token_secret'; then
    write_env "TOKEN_SECRET" "$(bashio::config 'token_secret')"
fi

if bashio::config.has_value 'env_vars'; then
    bashio::log.info "Setting custom environment variables"
    ENV_VARS=$(bashio::config 'env_vars')
    for env_var in $ENV_VARS; do
        VAR_NAME=$(echo "$env_var" | jq -r '.name')
        VAR_VALUE=$(echo "$env_var" | jq -r '.value // empty')
        if [ -n "$VAR_NAME" ] && [ -n "$VAR_VALUE" ]; then
            echo "${VAR_NAME}=${VAR_VALUE}" >> "$ENV_FILE"
            bashio::log.info "Added env var: $VAR_NAME"
        fi
    done
fi

for folders in /etc/services.d /etc/s6-overlay; do
    [[ -d "$folders" ]] && rm -r "$folders"
done

bashio::log.info "Configuration generated at ${ENV_FILE}"
bashio::log.info "Starting LightRAG server..."

cd /app || {
    bashio::log.red "Cannot change to /app directory"
    exit 1
}

exec python -m lightrag.api.lightrag_server
