arch:
  - aarch64
  - amd64
description: "Apprise API - based on linuxserver/docker-apprise-api"
homeassistant: "2024.1.0"
icon: icon.png
image: ghcr.io/rezusnet/apprise-api-{arch}
init: false
name: Apprise API
options:
  PGID: 0
  PUID: 0
  TZ: ""
  data_location: /share/apprise-api
  env_vars: []
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: "Web interface"
schema:
  PGID: int
  PUID: int
  TZ: str?
  data_location: str
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
ingress: true
ingress_port: 8000
panel_icon: mdi:server
slug: apprise-api
url: https://github.com/linuxserver/docker-apprise-api
version: 1.0.0
