arch:
  - aarch64
  - amd64
description: "Kometa - based on linuxserver/docker-kometa"
homeassistant: "2024.1.0"
icon: icon.png
image: ghcr.io/rezusnet/kometa-{arch}
init: false
name: Kometa
options:
  PGID: 0
  PUID: 0
  TZ: ""
  data_location: /share/kometa
  env_vars: []
ports:
  8191/tcp: 8191
ports_description:
  8191/tcp: "Web interface"
schema:
  PGID: int
  PUID: int
  TZ: str?
  data_location: str
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
ingress: true
ingress_port: 8191
panel_icon: mdi:server
slug: kometa
url: https://github.com/linuxserver/docker-kometa
version: 1.0.0
