name: Issue linker

on:
  issues:
    types: [opened, edited, closed]
  workflow_dispatch:

jobs:
  issues-linked:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Assign issues
        run: |
          echo "Starting"
          ALL_ISSUES=""
          PAGE=1
          while true; do
            RESPONSE=$(curl -s -L "https://api.github.com/repos/rezusnet/hassio-addons/issues?per_page=100&page=$PAGE")
            if [ "$(echo "$RESPONSE" | jq 'length')" = "0" ]; then
              break
            fi
            ALL_ISSUES="${ALL_ISSUES}${RESPONSE}"
            PAGE=$((PAGE + 1))
          done
          echo "$ALL_ISSUES" | jq -s 'flatten' > issueslist
          for f in $( find -- * -maxdepth 0 -type d | sort -r ); do
            if [ -f "$f"/config.yaml ] && [ -f "$f"/README.md ]; then
              sed -i "/Open Issue :/d" "$f"/README.md
              sed -i "/Open Request :/d" "$f"/README.md
              COUNTER=0
              while [[ $(jq -r --arg COUNTER "$COUNTER" ".[$COUNTER].title" issueslist) != null ]]; do
                (( COUNTER=COUNTER+1 )) || true
                TITLE="$(jq -r --arg COUNTER "$COUNTER" ".[$COUNTER].title" issueslist)"
                TITLE="${TITLE//[<>\$\'\"]/}"
                SLUG="$(grep -r "slug:" "$f"/config.yaml | awk '{print $2}')"
                NAME="$(grep -r "^name:" "$f"/config.yaml | awk '{print $2}')"
                if [[ "${TITLE,,}" == *"${f,,}"* ]] || [[ "${TITLE,,}" == *"${SLUG,,}"* ]] || [[ "${TITLE,,}" == *"${NAME,,}"* ]]; then
                  REQ="$(jq -r --arg COUNTER "$COUNTER" ".[$COUNTER].user.login" issueslist)"
                  URL="$(jq -r --arg COUNTER "$COUNTER" ".[$COUNTER].html_url" issueslist)"
                  LABEL="$(jq -r --arg COUNTER "$COUNTER" ".[$COUNTER].labels[].name" issueslist)"
                  DATEISSUE="$(jq -r --arg COUNTER "$COUNTER" ".[$COUNTER].created_at" issueslist)"
                  DATEISSUE="${DATEISSUE%T*}"
                  if [[ "$LABEL" == *"bug"* ]]; then
                    sed -i "1i ## Open Issue : [$TITLE (opened ${DATEISSUE})]($URL) by [@${REQ}](https://github.com/$REQ)" "$f"/README.md
                  elif [[ "$LABEL" == *"enhancement"* ]]; then
                    sed -i "1i ## Open Request : [$TITLE (opened ${DATEISSUE})]($URL) by [@${REQ}](https://github.com/$REQ)" "$f"/README.md
                  fi
                fi
              done
            fi
          done
          rm issueslist
      - name: Commit if needed
        uses: EndBug/add-and-commit@v10
        with:
          message: "Github bot: issues linked to readme"
          default_author: github_actions
          commit: -u
          fetch: --force
          push: --force
